name: 'Build & Test'
on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build

  job_size_check:
    name: Size Check
    needs: job_build
    runs-on: ubuntu-latest
    if: ${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - uses: andresz1/size-limit-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build

  job_lint:
    name: Lint
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Run Linter
        run: yarn lint

  job_unit_test:
    name: Test
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Unit Tests
        run: yarn test
      - uses: codecov/codecov-action@v1

  job_browserstack_test:
    name: BrowserStack
    needs: job_build
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Integration Tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          cd packages/browser
          yarn test:integration:checkbrowsers
          yarn test:integration
          yarn test:package

  job_zeus:
    name: Zeus
    needs: job_build
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'release/')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Install Zeus
        run: |
          yarn global add @zeus-ci/cli
          echo "::add-path::$(yarn global bin)"
      - name: Upload to Zeus
        env:
          ZEUS_API_TOKEN: ${{ secrets.ZEUS_API_TOKEN }}
          ZEUS_HOOK_BASE: ${{ secrets.ZEUS_HOOK_BASE }}
        run: |
          zeus job update -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA
          yarn pack:changed
          zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/tar+npm" ./packages/**/*.tgz
          zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/javascript" ./packages/browser/build/*
          zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/javascript" ./packages/integrations/build/*
          zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/javascript" ./packages/apm/build/*
          zeus upload -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -t "application/javascript" ./packages/tracing/build/*
          zeus job update --status=passed -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA

  job_artifacts:
    name: Artifacts Upload
    needs: job_build
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'release/')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Pack
        run: yarn pack:changed
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/packages/browser/build/**
            ${{ github.workspace }}/packages/integrations/build/**
            ${{ github.workspace }}/packages/apm/build/**
            ${{ github.workspace }}/packages/tracing/build/**
            ${{ github.workspace }}/packages/**/*.tgz
